namespace: istio-system
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/environment: dev
      app.kubernetes.io/part-of: infra

resources:
  - ../base/cadvisor/
  - ../base/kube-state-metrics/
  - ../base/node-exporter/
  - ../base/prometheus/
  - ../base/kiali/
  - ../base/grafana/
  - ../base/jaeger/
