labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: observability
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/version: v2.48.0
# https://github.com/appscode/third-party-tools/tree/master/monitoring/prometheus/builtin

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
