apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - name: http-prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
