apiVersion: v1
kind: Service
metadata:
  name: productpage
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9080"
    prometheus.io/path: "/metrics"
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app.kubernetes.io/name: productpage
