labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/instance: node-exporter
      app.kubernetes.io/version: 1.9.0

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - daemonset.yaml
  - service.yaml
