apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'
    prometheus.io/path: '/metrics'
spec:
  ports:
    - name: http
      port: 9100
      targetPort: 9100
  selector:
    app.kubernetes.io/name: node-exporter
