labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: observability
      app.kubernetes.io/name: kiali
      app.kubernetes.io/instance: kiali
      app.kubernetes.io/version: v2.6.0
# https://kiali.io/

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
