apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
    # Note: Change port name if you add '--query.grpc.tls.enabled=true'
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
  selector:
    app.kubernetes.io/name: jaeger
