labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/instance: kube-state-metrics
      app.kubernetes.io/version: 2.15.0

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - daemonset.yaml
  - service.yaml
