apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
data:

  grafana.ini: |
    [analytics]
    check_for_updates = true
    
    [grafana_net]
    url = https://grafana.istio-system.svc.cluster.local:3000
    
    [log]
    mode = console
    
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    
    [server]
    domain = ''
    
    [date_formats]
    default_timezone = UTC

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 15s
      name: Prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus.istio-system.svc.cluster.local:9090
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        timeInterval: 5s
      name: Loki
      orgId: 1
      type: loki
      url: http://loki:3100

  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      folder: istio
      name: istio
      options:
        path: /var/lib/grafana/dashboards/istio
      orgId: 1
      type: file
    - disableDeletion: false
      folder: istio
      name: istio-services
      options:
        path: /var/lib/grafana/dashboards/istio-services
      orgId: 1
      type: file
